# Generated by Django 3.1.2 on 2020-10-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_auto_20201022_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
