# Generated by Django 3.1.2 on 2020-10-22 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_hotel_proveedor_restaurante_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resta_Prove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Restaurante')),
                ('re_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.restaurante_proveedor', verbose_name='Proveedor Restaurante')),
            ],
        ),
    ]
